name: flutter_hyphen
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.13.2
  flutter: ">=1.17.0"

dependencies:
  characters: ^1.4.1
  flutter:
    sdk: flutter
  hyphen: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

